# Generated by Django 2.2 on 2019-04-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.IntegerField(max_length=5)),
                ('cliente', models.CharField(max_length=300)),
                ('servico', models.TextField()),
                ('quant', models.DecimalField(decimal_places=0, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('entrada', models.DateField()),
                ('vendedor', models.CharField(max_length=100)),
                ('op', models.IntegerField(max_length=5)),
                ('prev_entrega', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload_list_op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('arquivo', models.FileField(max_length=200, upload_to='static/arquivosxls/')),
            ],
        ),
        migrations.CreateModel(
            name='Reg_entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.DateField(blank=True, null=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('op', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='modulopcp.Ops')),
            ],
        ),
    ]
