# Generated by Django 2.2 on 2019-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relacao_op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc', models.IntegerField(max_length=5)),
                ('cliente', models.CharField(max_length=300)),
                ('servico', models.CharField(max_length=400)),
                ('quant', models.IntegerField(max_length=8)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=8)),
                ('entrada', models.DateField()),
                ('vendedor', models.CharField(max_length=200)),
                ('op', models.CharField(max_length=200)),
                ('prev_entrega', models.DateField()),
                ('nota', models.CharField(max_length=200)),
                ('entrega', models.DateField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('finalizada', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
