# Generated by Django 2.2 on 2019-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testexls3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=200)),
                ('campo2', models.CharField(max_length=200)),
            ],
        ),
    ]
