# Generated by Django 2.2 on 2019-04-27 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadxls',
            name='arquivo',
            field=models.FileField(default=datetime.datetime(2019, 4, 27, 19, 24, 6, 591782, tzinfo=utc), max_length=200, upload_to='xls/'),
            preserve_default=False,
        ),
    ]
