# Generated by Django 2.2 on 2019-04-28 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='prev_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
