# Generated by Django 2.2 on 2019-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_entrega',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
