# Generated by Django 2.2 on 2019-04-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_entrega',
            name='op',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='modulopcp.Ops'),
        ),
    ]
