# Generated by Django 2.2 on 2019-04-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ops',
            name='valor',
        ),
    ]
