# Generated by Django 2.2 on 2019-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0002_testexls3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_list_op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('arquivo', models.FileField(max_length=200, upload_to='static/arquivosxls/')),
            ],
        ),
    ]
