# Generated by Django 2.2 on 2019-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0002_remove_ops_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
