# Generated by Django 2.2 on 2019-04-28 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0002_ops_prev_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='info_fat',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
