# Generated by Django 2.2 on 2019-04-28 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0003_ops_info_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ops',
            name='entrega',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
