# Generated by Django 2.2 on 2019-04-28 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0003_ops_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='entrada',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ops',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
