# Generated by Django 2.2 on 2019-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0004_auto_20190428_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ops',
            name='entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
