# Generated by Django 2.2 on 2019-04-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulopcp', '0005_auto_20190428_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ops',
            name='info_fat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
