# Generated by Django 2.1.7 on 2019-04-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0009_orcamento_filme_acabamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orc_adesivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField()),
                ('servico', models.CharField(max_length=400)),
                ('comp', models.DecimalField(decimal_places=0, max_digits=3)),
                ('larg', models.DecimalField(decimal_places=0, max_digits=3)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=7)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Acabamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Cliente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Adesivo')),
            ],
        ),
        migrations.AlterField(
            model_name='filme_bopp',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Tpfilme'),
        ),
        migrations.AlterField(
            model_name='orcamento_adesivo',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Acabamento'),
        ),
        migrations.AlterField(
            model_name='orcamento_adesivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento_adesivo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Adesivo'),
        ),
        migrations.AlterField(
            model_name='orcamento_filme',
            name='acabamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moduloof.Acabamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento_filme',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento_filme',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Filme_bopp'),
        ),
    ]
