# Generated by Django 2.1.7 on 2019-04-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0010_auto_20190402_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orc_adesivo',
            name='acabamento',
        ),
        migrations.RemoveField(
            model_name='orc_adesivo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orc_adesivo',
            name='material',
        ),
        migrations.DeleteModel(
            name='Orc_adesivo',
        ),
    ]
