# Generated by Django 2.2 on 2019-04-23 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0011_auto_20190406_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloof.Tpadesivo'),
        ),
    ]
