# Generated by Django 2.2.1 on 2019-08-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_upload_xls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload_list_opv2',
            new_name='Upload_list_op',
        ),
        migrations.RemoveField(
            model_name='reg_entregav2',
            name='op',
        ),
        migrations.DeleteModel(
            name='Opsv2',
        ),
        migrations.DeleteModel(
            name='Reg_entregav2',
        ),
    ]
